"""First Migration Test

Revision ID: 658896f61f71
Revises: 
Create Date: 2026-09-22 00:24:26.991004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658896f61f71'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'display_image',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(op.f('seats_section_id_code_key'), 'seats', type_='unique')
    op.create_unique_constraint('unique_seat_constraint', 'seats', ['section_id', 'code'])
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('venues', 'display_image',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'display_image',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('unique_seat_constraint', 'seats', type_='unique')
    op.create_unique_constraint(op.f('seats_section_id_code_key'), 'seats', ['section_id', 'code'], postgresql_nulls_not_distinct=False)
    op.alter_column('events', 'display_image',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
