"""Full Text Search

Revision ID: 6c09047178f4
Revises: 15518abaa89d
Create Date: 2026-09-22 23:59:27.101378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c09047178f4'
down_revision: Union[str, Sequence[str], None] = '15518abaa89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, ''))", persisted=True), nullable=False))
    op.drop_index(op.f('idx_events_name_venue'), table_name='events')
    op.create_index('idx_events_tsv', 'events', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_tsv', table_name='events', postgresql_using='gin')
    op.create_index(op.f('idx_events_name_venue'), 'events', ['name', 'venue_id'], unique=False)
    op.drop_column('events', 'tsv')
    # ### end Alembic commands ###
